### PR TITLE
Add GitHub actions based minimal ci with test updates

### PR DESCRIPTION
**Pull request by ryoqun**

### CODE REVIEW

**Comment by QuarticCat** [comment]
Are you sure the action works？ I cannot see rust toolchain installation. BTW you might want to use rust-cache to speed up CI.

**Comment by QuarticCat** [comment]
This project could help testing GitHub actions: https://github.com/nektos/act

**Comment by ryoqun** [comment]
@QuarticCat 

> Are you sure the action works？ I cannot see rust toolchain installation.

yeah, i tested: https://github.com/ryoqun/enum-ptr/pull/1
github vm images have built-in rust toolchain which is decently up-to-date.

>  BTW you might want to use rust-cache to speed up CI.

as you can see the above sample run, it finished within minutes. so i think it's not needed for now. :)

**Comment by ryoqun** [comment]
> This project could help testing GitHub actions: https://github.com/nektos/act

heh, today i learnt. thanks for the tip.

**Comment by QuarticCat** [comment]
Fair. Then it looks good to me now.

**Review by QuarticCat — APPROVED** [review]

**Pull request merged**
